import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import NavBar from "@/components/nav-bar";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Next Todo App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <NavBar className="sticky top-0" />
          <main className="mb-6 mt-3 px-4">{children}</main>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
